### ISSUE TITLE
支持查看任务执行历史

### ISSUE THREAD

**Issue by NighterCoder** [MeetYouDevs/big-whale#45]
目前创建一个任务是将记录保存至scheduling中，而在每一次调度执行的时候，是在scheduling表中原记录进行更新操作，这样设计是不是无法查询任务的执行历史

**Comment by NighterCoder** [comment]
是不是可以考虑增加一张scheduling_history表

**Comment by progr1mmer** [comment]
> 是不是可以考虑增加一张scheduling_history表

后续版本添加
