### ISSUE TITLE
队列无法选择

### ISSUE THREAD

**Issue by iwasjoker** [MeetYouDevs/big-whale#60]
你好！
    我在使用离线调度时，有时候会出现无法选择设置完成的队列的情况，不知道是否遇到过

**Comment by progr1mmer** [comment]
> 你好！
> 我在使用离线调度时，有时候会出现无法选择设置完成的队列的情况，不知道是否遇到过

你是不是先打开编辑页面在创建的丢列，如果是的话，你添加完队列要刷新一下编辑页面

**Comment by iwasjoker** [comment]
> > 你好！
> > 我在使用离线调度时，有时候会出现无法选择设置完成的队列的情况，不知道是否遇到过
> 
> 你是不是先打开编辑页面在创建的队列，如果是的话，你添加完队列要刷新一下编辑页面

你好，我的操作步骤：集群管理 ---> 集群用户 ---> 新增用户中添加队列 ---> 离线调度 ---> xin> 你好！
> > 我在使用离线调度时，有时候会出现无法选择设置完成的队列的情况，不知道是否遇到过
> 
> 你是不是先打开编辑页面在创建的队列，如果是的话，你添加完队列要刷新一下编辑页面

我晓得问题出在哪里了，队列和当前登录用户有关，我在另一个用户下创建的队列，当前用户选择的时候并不会显示
